"""Package real Unity replay traces into an offline, camera-free diagnostic viewer."""
import json
from pathlib import Path
root=Path(__file__).resolve().parents[1]
folder=root/'artifacts/pose-tests/stability'
data={name:{phase:json.loads((folder/f'{name}-{phase}.json').read_text()) for phase in ('before','after')} for name in ('p1','p2')}
html=r'''<!doctype html><meta charset="utf-8"><title>Kinesthetic · pose diagnostics</title>
<style>body{margin:0;background:#101a26;color:#e7f3ff;font:16px system-ui;padding:30px}h1{margin:0 0 8px}p{color:#b1c2d3}button,select{background:#243d56;border:1px solid #6889a9;color:white;padding:10px 18px;border-radius:8px;margin-right:8px}canvas{width:100%;background:#172536;border-radius:16px}main{max-width:1250px;margin:auto}.grid{display:grid;grid-template-columns:1fr 1fr;gap:20px}input{width:100%;margin:20px 0}pre{white-space:pre-wrap;background:#1c3043;padding:16px;border-radius:12px;font-size:14px}small{color:#8facc6}h2{font-size:20px}</style>
<main><h1>Pose → Mii: recorded-motion diagnostics</h1><p>Your saved p1 / p2 clips. No camera access. Raw coordinates are unchanged; filtering affects avatar presentation only. Club rotation in these recorded previews is estimated from the arms; live calibrated play uses the AirPod.</p>
<div class="grid"><section><h2>P1 · seated / compact grip</h2><video controls preload="metadata" src="p1-grip-clean.mp4?v=1" style="width:100%;max-height:460px;border-radius:12px"></video></section><section><h2>P2 · standing / revised swing</h2><video controls preload="metadata" src="p2-standing-grip-v4.mp4?v=1" style="width:100%;max-height:460px;border-radius:12px"></video></section></div><p><a href="p1-grip-fixed.mp4">Earlier P1</a> · <a href="p2-side-by-side-v4.mp4">P2 side by side with source</a> · <a href="p2-standing-grip-v2.mp4">Earlier P2</a> for comparison.</p><h2>Landmark and rotation diagnostics</h2><select id="clip"><option value="p1">P1 · seated</option><option value="p2">P2 · standing</option></select><button id="play">Play</button><select id="rate"><option value="0.5">Half speed</option><option value="1">Normal speed</option></select><select id="plane"><option value="xy">Front X/Y</option><option value="zy">Side Z/Y · inspect depth</option></select><span id="time"></span>
<input id="seek" type="range" min="0" value="0"><div class="grid"><section><h2>Raw MediaPipe landmarks</h2><canvas id="raw" width="600" height="550"></canvas><pre id="rawData"></pre></section><section><h2>Filtered presentation landmarks</h2><canvas id="filtered" width="600" height="550"></canvas><pre id="filteredData"></pre></section></div><pre id="rotations"></pre><small>Dim joints have low confidence or lie outside the image. Briefly held joints are never counted as fresh tracking. The before/after bone steps are measured on the actual Unity rigs; lower steps do not establish anatomical accuracy.</small></main>
<script>const DATA=__DATA__;
const $=id=>document.getElementById(id),edges=[[11,12],[11,13],[13,15],[12,14],[14,16],[11,23],[12,24],[23,24],[23,25],[25,27],[24,26],[26,28]];
let index=0,playing=false,last=0,elapsed=0;
function angle(a,b){let d=Math.abs(a.reduce((v,x,i)=>v+x*b[i],0));return 2*Math.acos(Math.min(1,d))*180/Math.PI;}
function draw(id,points,img){const c=$(id),g=c.getContext('2d');g.clearRect(0,0,c.width,c.height);if(!points)return;const project=p=>[300+p[$('plane').value[0]]*260,295+p.y*260];g.strokeStyle='#294157';g.lineWidth=1;for(let x=40;x<600;x+=52){g.beginPath();g.moveTo(x,0);g.lineTo(x,550);g.stroke();}for(const [a,b]of edges){if(!points[a]||!points[b])continue;const p=project(points[a]),q=project(points[b]);g.strokeStyle=id==='raw'?'#e9b879':'#6be0ce';g.globalAlpha=img[a]?.visibility>=.5&&img[b]?.visibility>=.5?1:.2;g.lineWidth=5;g.beginPath();g.moveTo(...p);g.lineTo(...q);g.stroke();}g.globalAlpha=1;for(let i=11;i<=28;i++){if(!points[i])continue;const p=project(points[i]);g.fillStyle=i===15||i===16?'#fff':'#64b7ee';g.beginPath();g.arc(...p,5,0,7);g.fill();}}
function vec(p){return !p?'unavailable':[p.x,p.y,p.z].map(x=>Number(x).toFixed(3)).join(', ')}
function render(){const d=DATA[$('clip').value],a=d.after.trace[index],b=d.before.trace[index],prior=Math.max(0,index-1);$('seek').max=d.after.trace.length-1;$('seek').value=index;$('time').textContent=(a.timeMs/1000).toFixed(2)+' s';draw('raw',a.raw,a.image);draw('filtered',a.filtered,a.image);$('rawData').textContent=`Left wrist XYZ:  ${vec(a.raw[15])}\nRight wrist XYZ: ${vec(a.raw[16])}\nVisibility L/R: ${a.image[15]?.visibility.toFixed(2)} / ${a.image[16]?.visibility.toFixed(2)}`;$('filteredData').textContent=`Left wrist XYZ:  ${vec(a.filtered?.[15])}\nRight wrist XYZ: ${vec(a.filtered?.[16])}\nCurrent arms accepted: left ${a.left}, right ${a.right}\nUnavailable/rejected joints: ${a.rejected}`;$('rotations').textContent='BONE                   BEFORE STEP    AFTER STEP (degrees)\n'+d.after.stats.map((s,i)=>s.bone.padEnd(22)+angle(d.before.trace[prior].rotations[i],b.rotations[i]).toFixed(2).padStart(10)+angle(d.after.trace[prior].rotations[i],a.rotations[i]).toFixed(2).padStart(14)).join('\n')+'\n\nCurrent solved chest quaternion: '+a.rawChest.map(x=>x.toFixed(3)).join(', ')+'\nRendered chest quaternion:       '+a.rotations[0].map(x=>x.toFixed(3)).join(', ');}
$('clip').onchange=()=>{index=0;elapsed=0;render()};$('seek').oninput=()=>{index=+$('seek').value;elapsed=DATA[$('clip').value].after.trace[index].timeMs;render()};$('plane').onchange=render;$('play').onclick=()=>{playing=!playing;$('play').textContent=playing?'Pause':'Play';last=0};function tick(t){if(playing){if(last)elapsed+=(t-last)*+$('rate').value;const frames=DATA[$('clip').value].after.trace;if(elapsed>frames.at(-1).timeMs){elapsed=0;index=0;}while(index<frames.length-1&&frames[index+1].timeMs<=elapsed)index++;render();}last=t;requestAnimationFrame(tick)}render();requestAnimationFrame(tick);
</script>'''
(folder/'index.html').write_text(html.replace('__DATA__',json.dumps(data,separators=(',',':'))))
print(folder/'index.html')
